FROM golang:1.22 AS build
WORKDIR /api-wrapper
COPY ./ ./
RUN go mod download
RUN go build -o api-wrapper .

FROM ubuntu:22.04
WORKDIR /
RUN apt update && apt install git -y
RUN git clone https://github.com/BumbleB-NL/gamekube.git
COPY --from=build /api-wrapper/api-wrapper /usr/local/bin
COPY config /kubeconfig/config
CMD ["api-wrapper"]