apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - protocol: UDP
      port: 34197
      targetPort: 34197
  type: LoadBalancer