allowVolumeExpansion: false
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    field.cattle.io/description: nfs-storage
  creationTimestamp: '2024-03-01T13:44:47Z'
  managedFields:
    - apiVersion: storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:allowVolumeExpansion: {}
        f:metadata:
          f:annotations:
            .: {}
            f:field.cattle.io/description: {}
        f:mountOptions: {}
        f:parameters:
          .: {}
          f:server: {}
          f:share: {}
        f:provisioner: {}
        f:reclaimPolicy: {}
        f:volumeBindingMode: {}
      manager: agent
      operation: Update
      time: '2024-03-01T13:44:47Z'
  name: nfs-storage
  resourceVersion: '12033'
  uid: 432f766f-7211-4559-9165-a541ab6996dc
mountOptions:
  - nfsvers=4.1
parameters:
  server: 10.200.0.9
  share: /mnt/P1-K1-Pool01
provisioner: nfs.csi.k8s.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
