# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths: KubeServices/
  pull_request:
    branches: [ "main" ]
    paths: KubeServices/

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create_tgz_release_assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create TGZ files
        run: |
          for dir in KubeServices/*; do
            echo "Tarring directory: $dir"
            base=$(basename "$dir")
            echo "Base directory: $base"
            tar -czf "tgz_files/$base.tgz" "$dir"
          done
      - name: Debug - List Contents of KubeServices Directory
        run: ls KubeServices/

      - name: Debug - List Contents of KubeServices Directory
        run: ls ./

      - name: Debug - List Contents of KubeServices Directory
        run: ls KubeServices/gamekube-factorio


      # Add the .tgz files to the repository
      - name: Add .tgz files to the repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add tgz_files/
          git commit -m "Add .tgz files"
          git push
