# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths: KubeServices/
  pull_request:
    branches: [ "main" ]
    paths: KubeServices/

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create_tgz_release_assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create TGZ files
        run: |
          for dir in KubeServices/*; do
            echo "Tarring directory: $dir"
            base=$(basename "$dir")
            echo "Base directory: $base"
            tar -czf "tgz_files/$base.tgz" "$dir"
          done

      - name: Debug - List Contents of KubeServices Directory
        run: ls KubeServices/

      - name: Debug - List Contents of KubeServices Directory
        run: ls ./

      - name: Debug - List Contents of KubeServices Directory
        run: ls KubeServices/gamekube-factorio
        
      - name: Create TGZ files
        run: |
          for dir in KubeServices/*; do
            echo "Tarring directory: $dir"
            base=$(basename "$dir")
            echo "Base directory: $base"
            # Change working directory to the directory being archived
            cd "$dir"
            # Create .tgz file without including the top-level directory
            tar -czf "../tgz_files/$base.tgz" .
            # Return to the previous directory
            cd -
          done
